In [1]:
#overall requirement https://github.com/Teddy-XiongGZ/ProtoCell4P/blob/main/requirements.txt
# matplotlib==3.6.2 # seaborn==0.12.1 # torch==1.13.1 # pandas==1.5.2 # numpy==1.23.4 # scikit-learn==1.2.0 
# scipy==1.9.3 # tqdm==4.64.1 # scanpy==1.9.1 # goatools==1.2.4 # tensorboard
#%reset

In [2]:
from config_cytof_ver010 import Config
import torch

#input_arg has arguments_for_protocell and arguments_for_visualize
from input_args import *   

In [3]:
from datetime import datetime
now = datetime.now()
current_time = now.strftime("%H_%M_%S")
import datetime
today = datetime.date.today()

In [4]:
seed_numb = 121
global seed_numb

log_file_name = 'log_' + str(today) + '_' + str(current_time) + "_" + str(seed_numb) + ".txt"
print(log_file_name)

data_folder_name = 'rh2_cf5_tcell_dim22_allcond_imp_v_noimp'
data_loc_str = '../data/'+ data_folder_name

exp_string = 'protocell_cytof_'+ data_folder_name + '_' + str(seed_numb)

lamb = 1.0

log_2024-02-05_13_05_01_121.txt


In [5]:
#lambda_5 and lambda_6 are related to load_ct
args = arguments_for_protocell(data = "cytof",
                               data_loc = data_loc_str,
                               model = "ProtoCell",
                               seed = seed_numb,
                               exp_str = exp_string,
                               log_file_name = log_file_name,
                               h_dim = 16,
                               z_dim = 8,
                               n_layers = 2, 
                               n_proto = 15,
                               split_ratio = [0.5, 0.25, 0.25], #[0.5, 0.25, 0.25] #0.70834 + 0.04166  +0.25
                               max_epoch = 2800,
                               batch_size = 500,
                               subsample = False,
                               eval = None,
                               pretrained = False, #False is good
                               max_epoch_pretrain = 30,
                               keep_sparse = False,
                               lr = 0.0005,
                               device = "cuda:0", #"cpu", #device = "cuda:0",
                               load_ct = True,
                               lambda_1 = lamb, lambda_2 = lamb, lambda_3 = lamb, 
                               lambda_4 = lamb, lambda_5 = lamb, lambda_6 = lamb)

In [6]:
torch.manual_seed(seed_numb)
torch.cuda.manual_seed(seed_numb)

config = Config(
        data = args.data,
        data_loc = args.data_loc,
        log_file_name = args.log_file_name,
        model = args.model,
        split_ratio = args.split_ratio,
        lr = args.lr,
        max_epoch = args.max_epoch,
        batch_size = args.batch_size,
        test_step = args.test_step,
        h_dim = args.h_dim,
        z_dim = args.z_dim,
        n_layers = args.n_layers,
        n_proto = args.n_proto,
        device = args.device,
        seed = args.seed,
        exp_str = args.exp_str,
        task = args.task,
        subsample = False if args.subsample is None else args.subsample,
        eval = False if args.eval is None else args.eval,
        load_ct = False if args.load_ct is None else args.load_ct,
        d_min = args.d_min,
        lambda_1 = args.lambda_1,
        lambda_2 = args.lambda_2,
        lambda_3 = args.lambda_3,
        lambda_4 = args.lambda_4,
        lambda_5 = args.lambda_5,
        lambda_6 = args.lambda_6,
        keep_sparse = False if args.keep_sparse is None else args.keep_sparse,
        pretrained = False if args.pretrained is None else args.pretrained,
        lr_pretrain = args.lr_pretrain,
        max_epoch_pretrain = args.max_epoch_pretrain
)

loading data from../data/rh2_cf5_tcell_dim22_allcond_imp_v_noimp


100%|██████████| 16/16 [00:04<00:00,  3.26it/s]


[Size of dataset] IMPRV: 8 | NoIMP: 8

 training data set cell counts:
cell count: 25799, pat_id:1122  INPRV
cell count: 223162, pat_id:1034  INPRV
cell count: 102217, pat_id:1064  NoIMP
cell count: 156563, pat_id:1072  NoIMP
cell count: 118884, pat_id:1006  NoIMP
cell count: 153867, pat_id:1017  INPRV
cell count: 111811, pat_id:1013  INPRV
cell count: 76057, pat_id:1126  NoIMP

 validation data set cell counts:
cell count: 99436, pat_id:1007  INPRV
cell count: 78892, pat_id:1096  INPRV
cell count: 93515, pat_id:1018  NoIMP
cell count: 54582, pat_id:1009  INPRV

 test data set cell counts:
cell count: 61938, pat_id:1110  INPRV
cell count: 124755, pat_id:1073  NoIMP
cell count: 223449, pat_id:1068  NoIMP
cell count: 17351, pat_id:1047  NoIMP
Index([            1122,             1034,             1064,             1072,
                   1006,             1017,             1013,             1126,
                   1007,             1096,             1018,             1009,
            

In [7]:
# from torchinfo import summary
# summary(config.model)

In [8]:
%%time
# %%capture cap
config.train()

training :   0%|          | 1/2800 [00:01<1:04:02,  1.37s/ epoch]

[1 1 1 1 1 1 1 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :   4%|▎         | 102/2800 [01:29<38:46,  1.16 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :   7%|▋         | 201/2800 [02:56<37:59,  1.14 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  11%|█         | 301/2800 [04:24<36:50,  1.13 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  14%|█▍        | 401/2800 [05:52<35:21,  1.13 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  18%|█▊        | 501/2800 [07:20<33:41,  1.14 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  21%|██▏       | 601/2800 [08:48<32:21,  1.13 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  25%|██▌       | 701/2800 [10:16<30:45,  1.14 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  29%|██▊       | 801/2800 [11:44<29:08,  1.14 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  32%|███▏      | 901/2800 [13:13<27:57,  1.13 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  36%|███▌      | 1001/2800 [14:41<26:27,  1.13 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  39%|███▉      | 1101/2800 [16:09<24:55,  1.14 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  43%|████▎     | 1201/2800 [17:38<23:33,  1.13 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  46%|████▋     | 1301/2800 [19:08<22:14,  1.12 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  50%|█████     | 1401/2800 [20:36<20:36,  1.13 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  54%|█████▎    | 1501/2800 [22:06<19:13,  1.13 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  57%|█████▋    | 1601/2800 [23:34<17:35,  1.14 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  61%|██████    | 1701/2800 [25:03<16:13,  1.13 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  64%|██████▍   | 1801/2800 [26:31<14:38,  1.14 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  68%|██████▊   | 1901/2800 [28:00<13:08,  1.14 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  71%|███████▏  | 2001/2800 [29:29<12:52,  1.03 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  75%|███████▌  | 2101/2800 [30:57<10:23,  1.12 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  79%|███████▊  | 2201/2800 [32:25<08:47,  1.14 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  82%|████████▏ | 2301/2800 [33:53<07:19,  1.13 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  86%|████████▌ | 2401/2800 [35:21<05:51,  1.14 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  89%|████████▉ | 2501/2800 [36:50<04:22,  1.14 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  93%|█████████▎| 2601/2800 [38:19<02:57,  1.12 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training :  96%|█████████▋| 2701/2800 [39:47<01:27,  1.13 epoch/s]

[0 0 1 1 1 0 0 1]
tensor([0, 0, 1, 1, 1, 0, 0, 1])


training : 100%|██████████| 2800/2800 [41:15<00:00,  1.13 epoch/s]


tensor([0, 0, 1, 1], device='cuda:0')
config 409 y_truth 
tensor([0, 1, 1, 1])
config 409 y_pred with the best model at 2799
tensor([0, 0, 1, 1])
config 409 y_truth 
tensor([0, 1, 1, 1])
config 409 y_pred 
tensor([0, 0, 1, 1])
CPU times: user 1h 17min 2s, sys: 2h 43min 42s, total: 4h 45s
Wall time: 41min 15s


In [9]:
# args_var = vars(args)
# print(args_var)
# type(args_var)
# import pickle
# with open('args_var.pkl', 'wb') as file: 
#     # A new file will be created 
#     pickle.dump(args_var, file)

In [10]:
# config.model.parameters()

In [11]:
# for p in config.model.parameters():
#     if p.requires_grad:
#          print(p.name, p.data)