In [ ]:
#overall requirement https://github.com/Teddy-XiongGZ/ProtoCell4P/blob/main/requirements.txt
# matplotlib==3.6.2 # seaborn==0.12.1 # torch==1.13.1 # pandas==1.5.2 # numpy==1.23.4 # scikit-learn==1.2.0 
# scipy==1.9.3 # tqdm==4.64.1 # scanpy==1.9.1 # goatools==1.2.4 # tensorboard
#%reset

In [1]:
from config_cytof_ver013 import Config
import torch

#input_arg has arguments_for_protocell and arguments_for_visualize
from input_args import *  

In [2]:
from datetime import datetime
now = datetime.now()
current_time = now.strftime("%H_%M_%S")
import datetime
today = datetime.date.today()

In [3]:
global seed_numb
seed_numb = 123

pt_numb = 15
z_dime = 8

split_1 = round(0.5, 4)
split_2 = round( (1-split_1)/2, 5)
split_3 = round(1 - split_1 - split_2, 6)
split_ratio_input = [split_1, split_2, split_3]


log_file_name = 'log_' + str(today) + '_' + str(current_time) + "_" + str(seed_numb) + ".txt"
print(log_file_name)

data_folder_name = 'rh2_cf5_tcell_dim22_allcond_imp_v_noimp'
data_loc_str = '../data/'+ data_folder_name

exp_string1 = 'Prt_cytof_'+ data_folder_name 
exp_string2 = '_' + str(pt_numb) + 'pt_' + 'zd'+str(z_dime)+'_' + str(int(round(split_1*100,0)))  +'_spt1_sd' + str(seed_numb)
exp_string =  exp_string1 + exp_string2
print(exp_string)


lamb = 1.0

log_2024-05-16_23_11_59_123.txt
Prt_cytof_rh2_cf5_tcell_dim22_allcond_imp_v_noimp_15pt_zd8_50_spt1_sd123


In [4]:
#lambda_5 and lambda_6 are related to load_ct
args = arguments_for_protocell(data = "cytof",
                               data_loc = data_loc_str,
                               model = "ProtoCell",
                               seed = seed_numb,
                               exp_str = exp_string,
                               log_file_name = log_file_name,
                               h_dim = 16,
                               z_dim = z_dime,
                               n_layers = 2, 
                               n_proto = pt_numb,
                               test_step = 11,
                               split_ratio = split_ratio_input, #[0.5, 0.25, 0.25] #0.70834 + 0.04166  +0.25
                               max_epoch = 13,
                               batch_size = 500,
                               subsample = False,
                               eval = None,
                               pretrained = False, #False is good
                               max_epoch_pretrain = 30,
                               keep_sparse = False,
                               lr = 0.0005,
                               device = "cuda:0", #"cpu", #device = "cuda:0",
                               load_ct = True,
                               lambda_1 = lamb, lambda_2 = lamb, lambda_3 = lamb, 
                               lambda_4 = lamb, lambda_5 = lamb, lambda_6 = lamb)

In [5]:
torch.manual_seed(seed_numb)
torch.cuda.manual_seed(seed_numb)

config = Config(
        data = args.data,
        data_loc = args.data_loc,
        log_file_name = args.log_file_name,
        model = args.model,
        split_ratio = args.split_ratio,
        lr = args.lr,
        max_epoch = args.max_epoch,
        batch_size = args.batch_size,
        test_step = args.test_step,
        h_dim = args.h_dim,
        z_dim = args.z_dim,
        n_layers = args.n_layers,
        n_proto = args.n_proto,
        device = args.device,
        seed = args.seed,
        exp_str = args.exp_str,
        task = args.task,
        subsample = False if args.subsample is None else args.subsample,
        eval = False if args.eval is None else args.eval,
        load_ct = False if args.load_ct is None else args.load_ct,
        d_min = args.d_min,
        lambda_1 = args.lambda_1,
        lambda_2 = args.lambda_2,
        lambda_3 = args.lambda_3,
        lambda_4 = args.lambda_4,
        lambda_5 = args.lambda_5,
        lambda_6 = args.lambda_6,
        keep_sparse = False if args.keep_sparse is None else args.keep_sparse,
        pretrained = False if args.pretrained is None else args.pretrained,
        lr_pretrain = args.lr_pretrain,
        max_epoch_pretrain = args.max_epoch_pretrain
)

loading data from../data/rh2_cf5_tcell_dim22_allcond_imp_v_noimp


100%|██████████| 16/16 [00:05<00:00,  2.87it/s]


[Size of dataset] IMPRV: 8 | NoIMP: 8

 training data set cell counts:
cell count: 78892, pat_id:1096  INPRV
cell count: 76057, pat_id:1126  NoIMP
cell count: 61938, pat_id:1110  INPRV
cell count: 124755, pat_id:1073  NoIMP
cell count: 223449, pat_id:1068  NoIMP
cell count: 223162, pat_id:1034  INPRV
cell count: 25799, pat_id:1122  INPRV
cell count: 102217, pat_id:1064  NoIMP

 validation data set cell counts:
cell count: 99436, pat_id:1007  INPRV
cell count: 93515, pat_id:1018  NoIMP
cell count: 111811, pat_id:1013  INPRV
cell count: 54582, pat_id:1009  INPRV

 test data set cell counts:
cell count: 17351, pat_id:1047  NoIMP
cell count: 156563, pat_id:1072  NoIMP
cell count: 153867, pat_id:1017  INPRV
cell count: 118884, pat_id:1006  NoIMP
Index([            1096,             1126,             1110,             1073,
                   1068,             1034,             1122,             1064,
                   1007,             1018,             1013,             1009,
            

In [ ]:
from torchinfo import summary
summary(config.model)

In [6]:
# %%time
# %%capture cap
config.train()

training : 100%|██████████| 13/13 [00:09<00:00,  1.38 epoch/s]


tensor([1, 1, 1, 1], device='cuda:0')
config 409 y_truth 
tensor([1, 1, 0, 1])
config 409 y_pred with the best model at 10
tensor([1, 1, 1, 1])
config 409 y_truth 
tensor([1, 1, 0, 1])
config 409 y_pred 
tensor([1, 1, 1, 1])


In [ ]:
args_var = vars(args)
# print(args_var)
# type(args_var)
# import pickle
# with open('args_var.pkl', 'wb') as file: 
#     # A new file will be created 
#     pickle.dump(args_var, file)
import pickle
pickle_file_name='args_var_' + exp_string + '.pkl'
with open(pickle_file_name, 'wb') as file: 
    # A new file will be created 
    pickle.dump(args_var, file)

In [ ]:
# config.model.parameters()

In [ ]:
# for p in config.model.parameters():
#     if p.requires_grad:
#          print(p.name, p.data)

In [ ]:
seed_numb = 123
pt_numb = 18
z_dime = 16

split_1 = 0.55
split_ratio_input = [split_1, round((1-split_1)/2,5), round(1- split_1- round((1-split_1)/2,5),6)]

log_file_name = 'log_' + str(today) + '_' + str(current_time) + "_" + str(seed_numb) + ".txt"
print(log_file_name)

data_folder_name = 'CTA_Tcell_CAC_cut_at_105'
data_loc_str = '../data/'+ data_folder_name

exp_string = 'protocell_cytof_'+ data_folder_name + '_' + str(pt_numb) + '_55_' + str(seed_numb)

In [ ]:
split_ratio_input

In [ ]:
0.55+0.275+0.275

In [ ]:
split_1 = 0.55
split_ratio_input = [split_1, round((1-split_1)/2,5), round(1- split_1- round((1-split_1)/2,5),6)]

In [ ]:
split_ratio_input

In [ ]:
0.55 + 0.22499999999999998 + 0.22499999999999998 

In [ ]:
(0.55 + 0.22499999999999998 + 0.22499999999999998 )==(0.55+0.225+0.225)

In [ ]:
0.55+0.225+0.225

In [ ]:
0.224999999999999999999999999999999==0.225

In [ ]:
round(0.51)

In [ ]:
round(1.9999,3)

In [ ]:
split_1